# Generated by Django 3.2.6 on 2021-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('danceability', models.DecimalField(decimal_places=10, max_digits=10)),
                ('energy', models.DecimalField(decimal_places=10, max_digits=10)),
                ('key', models.IntegerField(max_length=3)),
                ('loudess', models.DecimalField(decimal_places=10, max_digits=10)),
                ('mode', models.IntegerField()),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=10)),
                ('instrumentalness', models.DecimalField(decimal_places=10, max_digits=10)),
                ('liveness', models.DecimalField(decimal_places=10, max_digits=10)),
                ('valence', models.DecimalField(decimal_places=10, max_digits=10)),
                ('tempo', models.DecimalField(decimal_places=10, max_digits=10)),
                ('duration_ms', models.BigIntegerField(max_length=10)),
                ('time_signture', models.IntegerField(max_length=5)),
                ('num_bars', models.IntegerField(max_length=5)),
                ('num_sections', models.IntegerField(max_length=5)),
                ('num_segments', models.IntegerField(max_length=5)),
                ('classes', models.IntegerField(max_length=5)),
                ('star_rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
