# Generated by Django 3.2.6 on 2021-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='acousticness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='danceability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='instrumentalness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='loudess',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='valence',
            field=models.FloatField(null=True),
        ),
    ]
