# Generated by Django 3.2.6 on 2021-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210922_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='classes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration_ms',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='num_bars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='num_sections',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='num_segments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='star_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='time_signture',
            field=models.IntegerField(null=True),
        ),
    ]
