# Generated by Django 3.2.6 on 2021-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_playlist_danceability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='loudess',
            new_name='loudness',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='danceability',
            field=models.FloatField(null=True),
        ),
    ]
