# Generated by Django 3.2.6 on 2021-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210922_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='index',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=100),
        ),
    ]
